version: "3.3"

services:
  mysqldb:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    image: benaouayene/project
    container_name: benaouayene/project
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
