version: "3.3"

services:
  mysqldb:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: on-failure
    ports:
      - 9099:9099
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
